# Generated by Django 4.1.2 on 2022-10-30 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=36)),
                ('username', models.CharField(max_length=24)),
                ('slug', models.SlugField()),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_application.task')),
            ],
        ),
    ]
