# Generated by Django 4.1.2 on 2022-10-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_application', '0002_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='to_do_application.task'),
        ),
    ]
