# Generated by Django 4.1.2 on 2022-10-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_application', '0005_remove_user_is_superuser_remove_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Username', max_length=24),
        ),
    ]
