# Generated by Django 4.1.2 on 2022-10-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_application', '0006_remove_user_login_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='null@null.com', max_length=64, unique=True),
        ),
    ]
