# Generated by Django 4.1.2 on 2022-11-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_application', '0011_task_description_task_is_public_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='to_do_application.usermodel'),
        ),
    ]
