# Generated by Django 4.1.2 on 2022-11-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_application', '0016_alter_usermodel_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_photo',
            field=models.ImageField(max_length=300, null=True, upload_to='profile-icon-9.png'),
        ),
    ]
